# Generated by Django 5.2.8 on 2025-11-24 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id_cancha', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('precioporHora', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'cancha',
            },
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipoactividad',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('ci', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('id_cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProyecto.cancha')),
                ('id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProyecto.tipoactividad')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProyecto.usuario')),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
    ]
