# Generated by Django 5.2.8 on 2025-11-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('mantenimiento', 'Mantenimiento')], default='disponible', max_length=20),
        ),
    ]
