# Generated by Django 5.2.8 on 2025-11-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProyecto', '0002_alter_cancha_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancha',
            name='precioporHora',
        ),
        migrations.AddField(
            model_name='tipoactividad',
            name='precioporHora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
